apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-template
  template:
    metadata:
      labels:
        app: service-template
    spec:
      containers:
        - name: service-template
          image: uhub.service.ucloud.cn/entropypool/service-template:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/ServiceTemplate
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: service-template-config
            items:
              - key: service-conf
                path: ServiceTemplate.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: service-template
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 32700
      targetPort: 32700
    - name: grpc
      port: 32701
      targetPort: 32701
    - name: prometheus
      port: 32702
      targetPort: 32702
  selector:
    app: service-template
