apiVersion: v1
kind: ConfigMap
metadata:
  name: account-gateway-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "account-gateway.npool.top"
      http_port: 50480
      grpc_port: 50481
      healthz_port: 50482
      prometheus_port: 50483
      appid: "89089012783789789719823798127398"
      serviceid: "b17b28e6-1e20-11ed-a4e1-93ed4cca7ac5"
      logdir: "./"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
